### ISSUE TITLE
How to install breakpoint-slicer when i use node-sass?

### ISSUE THREAD

**Issue by Zidcov** [lolmaus/breakpoint-slicer#18] opened 2015-11-11 14:24 UTC
npm install breakpoint-slicer  -g don't work

**Comment by lolmaus** [comment] 2015-11-11 14:26
npm install lolmaus/breakpoint-slicer#v1.3.6

I think you also want `--save-dev` instead of `-g`.

**Comment by Zidcov** [comment] 2015-11-11 14:37
Thanks for the reply. But I have not yet installed globally. Sleduushee leaves a message
```
Master@Master-PC MINGW64 /d/WebDevPjts/pR-LPs/lp-assess
$ npm install breakpoint-slicer
npm WARN package.json awesome_project@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "breakpoint-slicer"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/breakpoint-slicer
npm ERR! 404
npm ERR! 404 'breakpoint-slicer' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'awesome_project'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\WebDevPjts\pR-LPs\lp-assess\npm-debug.log

```

**Comment by lolmaus** [comment] 2015-11-12 14:17
@Zidcov Did you even try the command suggested by me?

**Comment by Zidcov** [comment] 2015-11-13 00:48
Yes, I tried.
Did ```npm install lolmaus/breakpoint-slicer#v1.3.6```
After  ```npm install breakpoint-slicer --save-dev ```
Unfortunately, did not work. I did my own mixins.
Thank you very much. I understand that it does not work under node-sass.
Alas I have not saved the error message.

**Comment by lolmaus** [comment] 2015-11-13 09:18
@Zidcov 

When you do `npm install lolmaus/breakpoint-slicer#v1.3.6`

it responds with `This command is not installed.`?

**Comment by Zidcov** [comment] 2015-11-13 10:11
Part of the error message is following:
```
..
npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Ma                 ster\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:l                 olmaus/breakpoint-slicer.git C:\Users\Master\AppData\Roaming\npm-cache\_git-remo                 tes\git-github-com-lolmaus-breakpoint-slicer-git-7b2d4685
npm ERR! Cloning into bare repository 'C:\Users\Master\AppData\Roaming\npm-cache                 \_git-remotes\git-github-com-lolmaus-breakpoint-slicer-git-7b2d4685'...
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
...
```
Full error log I post below

[npm-debug.txt](https://github.com/lolmaus/breakpoint-slicer/files/33825/npm-debug.txt)

My level of competence do not allow me to make a definite conclusion, unfortunately. 
Everything is possible because of my operating system with its long paths (Windows 7 64hom base) и node 4, npm 2.*

**Comment by lolmaus** [comment] 2015-11-13 10:42
Your git is not set up properly. This should help:

https://help.github.com/articles/generating-ssh-keys/#platform-windows

I'm closing this as your issue is not caused by `breakpoint-slicer`. But feel free to continue the discussion, I'll try to help.

**Closed by lolmaus** 2015-11-13 10:42 UTC

**Comment by Zidcov** [comment] 2015-11-14 11:50
@lolmaus, thank you

**Comment by lolmaus** [comment] 2015-11-21 15:09
I've just discovered that I was awfully wrong. Unlike Bower, npm won't install from a git repo if it doesn't contain a `package.json`.

I've created a `package.json` and published the project on npmjs.com.

You can now install it with:

    npm install --save-dev breakpoint-slicer

**Comment by Zidcov** [comment] 2015-11-21 16:04
@lolmaus , This is wonderful news. Thank you!
